apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefetcharr-config
  namespace: servarr
  labels:
    app: prefetcharr
    app.kubernetes.io/part-of: servarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    name: prefetcharr-config
    template:
      type: Opaque
      data:
        config.toml: |
          interval = 900
          log_level = "Info"
          prefetch_num = 2
          request_seasons = true
          connection_retries = 6

          [media_server]
          type = "Jellyfin"
          url = "http://jellyfin.jellyfin.svc.cluster.local:8096"
          api_key = "{{ .jellyfin_api_key }}"

          [sonarr]
          url = "http://sonarr.servarr.svc.cluster.local"
          api_key = "{{ .sonarr_api_key }}"
  data:
    - secretKey: jellyfin_api_key
      remoteRef:
        key: PREFETCHARR_JELLYFIN_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: sonarr_api_key
      remoteRef:
        key: PREFETCHARR_SONARR_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
