apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr
resources:
  - externalsecret-prefetcharr-config.yaml
  - deployment-prefetcharr-dev.yaml
  - deployment-prefetcharr.yaml
  - rbac-prefetcharr-ci.yaml
